# charge bibliotique

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

##import data

In [2]:
#connexion:
load_dotenv()  # installer .env
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db = os.getenv("DB_NAME")
DATABASE_URL = f"postgresql://{user}:{password}@{host}:{port}/{db}"
engine = create_engine(DATABASE_URL)
print("conexion ok")
df=pd.read_sql("select * from staging.jumia_data_raw",engine)

conexion ok

In [3]:
df

,Unnamed: 0,name,new_price,old_price,percent_discount,rate,verified_ratings,saler_score,Followers,Order Fulfillment_Rate,Quality Score,Customer Rating,link,page_number
0,0,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 299.00,47%,4.2,757.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
1,1,"Force Daily Backpack Laptop 14"" For Unisex - D...",EGP 159.00,EGP 245.00,35%,4.4,109.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/force-daily-backpack-...,1.0
2,2,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,134.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
3,3,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,128.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
4,4,"Force Daily Backpack Laptop 14"" For Unisex - Nod",EGP 159.00,EGP 245.00,35%,4.5,117.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/daily-backpack-for-un...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999,194,TAT Laptop Sleeve Case Cover Bag – Multicolor,EGP 199.00 - EGP 225.00,EGP 350.00,43%,NaN,NaN,94%,78.0,Excellent,Good,Excellent,https://www.jumia.com.eg/tat-laptop-sleeve-cas...,50.0
2000,195,SG SGLaptop - For 17 Inch Laptop - Black,EGP 580.00,None,None,NaN,NaN,60%,NaN,None,None,None,https://www.jumia.com.eg/sg-sglaptop-for-17-in...,50.0
2001,197,Samsung LC34G55TWWMXZN 34 Inch Odyssey WQHD 16...,"EGP 17,999.00",None,None,NaN,NaN,100%,84.0,Excellent,Excellent,None,https://www.jumia.com.eg/samsung-lc34g55twwmxz...,50.0
2002,198,Msa Fingerprint USB 3.0 Flash Drive (32GB) - D...,EGP 650.00,None,None,NaN,NaN,50%,30.0,Excellent,Very Poor,None,https://www.jumia.com.eg/fingerprint-usb-3.0-f...,50.0
2003,199,Apple MagSafe 2 Power Adapter For MacBook Pro...,"EGP 2,200.00",None,None,5.0,2.0,20%,431.0,Very Poor,Very Poor,Average,https://www.jumia.com.eg/60w-magsafe-2-power-a...,50.0

In [4]:
df.info() 
df.columns
df.shape
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2004 entries, 0 to 2003
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              2004 non-null   int64
 1   name                    1998 non-null   object
 2   new_price               1998 non-null   object
 3   old_price               1512 non-null   object
 4   percent_discount        1512 non-null   object
 5   rate                    723 non-null    float64
 6   verified_ratings        723 non-null    float64
 7   saler_score             1963 non-null   object
 8   Followers               1954 non-null   float64
 9   Order Fulfillment_Rate  1918 non-null   object
 10  Quality Score           1918 non-null   object
 11  Customer Rating         1483 non-null   object
 12  link                    1999 non-null   object
 13  page_number             1999 non-null   float64
dtypes: float64(4), int64(1), object(9)
memory usage: 219.3+ KB

,Unnamed: 0,name,new_price,old_price,percent_discount,rate,verified_ratings,saler_score,Followers,Order Fulfillment_Rate,Quality Score,Customer Rating,link,page_number
0,0,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 299.00,47%,4.2,757.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
1,1,"Force Daily Backpack Laptop 14"" For Unisex - D...",EGP 159.00,EGP 245.00,35%,4.4,109.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/force-daily-backpack-...,1.0
2,2,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,134.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
3,3,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,128.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
4,4,"Force Daily Backpack Laptop 14"" For Unisex - Nod",EGP 159.00,EGP 245.00,35%,4.5,117.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/daily-backpack-for-un...,1.0

In [8]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

Unnamed: 0                   0
name                         6
new_price                    6
old_price                  492
percent_discount           492
rate                      1281
verified_ratings          1281
saler_score                 41
Followers                   50
Order Fulfillment_Rate      86
Quality Score               86
Customer Rating            521
link                         5
page_number                  5
dtype: int64

## nettoyage

In [7]:
df

,Unnamed: 0,name,new_price,old_price,percent_discount,rate,verified_ratings,saler_score,Followers,Order Fulfillment_Rate,Quality Score,Customer Rating,link,page_number
0,0,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 299.00,47%,4.2,757.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
1,1,"Force Daily Backpack Laptop 14"" For Unisex - D...",EGP 159.00,EGP 245.00,35%,4.4,109.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/force-daily-backpack-...,1.0
2,2,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,134.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
3,3,Force 14-inch Laptop Daily Backpack For Unisex...,EGP 159.00,EGP 245.00,35%,4.3,128.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/14-inch-laptop-daily-...,1.0
4,4,"Force Daily Backpack Laptop 14"" For Unisex - Nod",EGP 159.00,EGP 245.00,35%,4.5,117.0,100%,1085.0,Excellent,Excellent,Excellent,https://www.jumia.com.eg/daily-backpack-for-un...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999,194,TAT Laptop Sleeve Case Cover Bag – Multicolor,EGP 199.00 - EGP 225.00,EGP 350.00,43%,NaN,NaN,94%,78.0,Excellent,Good,Excellent,https://www.jumia.com.eg/tat-laptop-sleeve-cas...,50.0
2000,195,SG SGLaptop - For 17 Inch Laptop - Black,EGP 580.00,None,None,NaN,NaN,60%,NaN,None,None,None,https://www.jumia.com.eg/sg-sglaptop-for-17-in...,50.0
2001,197,Samsung LC34G55TWWMXZN 34 Inch Odyssey WQHD 16...,"EGP 17,999.00",None,None,NaN,NaN,100%,84.0,Excellent,Excellent,None,https://www.jumia.com.eg/samsung-lc34g55twwmxz...,50.0
2002,198,Msa Fingerprint USB 3.0 Flash Drive (32GB) - D...,EGP 650.00,None,None,NaN,NaN,50%,30.0,Excellent,Very Poor,None,https://www.jumia.com.eg/fingerprint-usb-3.0-f...,50.0
2003,199,Apple MagSafe 2 Power Adapter For MacBook Pro...,"EGP 2,200.00",None,None,5.0,2.0,20%,431.0,Very Poor,Very Poor,Average,https://www.jumia.com.eg/60w-magsafe-2-power-a...,50.0